In [37]:
import pandas as pd, numpy as np
import time, utils

from sklearn.model_selection import train_test_split
# from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.preprocessing.text import Tokenizer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, mean_squared_error


In [20]:
### Load data
full_data = pd.read_csv('train.csv', header=0)
x_train, y_train = full_data['assignment'], full_data['grade']
y_train = y_train.astype(float)
print('y_train:\n', y_train)

y_train:
 0    10.0
1     8.0
2     4.0
3     5.0
4     5.0
5     5.0
Name: grade, dtype: float64


In [25]:
x_train = utils.clean_punctuation(x_train) # this also turns char to lowercase

### Turn to frequency vector
# convert each assignment into a feature vector representing the presence or absence of words from the vocabulary


# Create an instance of CountVectorizer
vectorizer = CountVectorizer()

# Fit the vectorizer on the assignments to build the vocabulary
vectorizer.fit(x_train)

# Transform the assignments into a matrix of feature vectors
x_train_feature_vectors = vectorizer.transform(x_train)

# Print the feature vectors
print(x_train_feature_vectors.toarray())

'''
(We are using sklearn.feature_extraction.text.CountVectorizer instead)

### Tokenize words 
# tokenizer = Tokenizer(  num_words = 100_000,
#                         filters   = '$&()+/<=>[\\]^_`{|}~\t')
# tokenizer.fit_on_texts(x_train) # Fit on the whole dataset because everything is available as we mark assignments

# # Really tokenizing
# x_train_sequences = []
# for seq in tokenizer.texts_to_sequences_generator(x_train):
#     x_train_sequences.append(seq)

# # Post-pad shorter sequences with 0 
# max_length = max([len(i) for i in x_train_sequences])
# x_train_tokenised = np.array(pad_sequences(x_train_sequences, maxlen=max_length, padding='post'))

# print('----------\nx_train_tokenised:\n', x_train_tokenised)
# Output looks like this:
#   [[ 8  9 10 11 12  0  0  0  0  0  0]
#    [ 1  2  3  4  5 13 14  6  7 15 16]]
'''

[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 1 1 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0]
 [0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 2 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 1 1]]


"\n(We are using sklearn.feature_extraction.text.CountVectorizer instead)\n\n### Tokenize words \n# tokenizer = Tokenizer(  num_words = 100_000,\n#                         filters   = '$&()+/<=>[\\]^_`{|}~\t')\n# tokenizer.fit_on_texts(x_train) # Fit on the whole dataset because everything is available as we mark assignments\n\n# # Really tokenizing\n# x_train_sequences = []\n# for seq in tokenizer.texts_to_sequences_generator(x_train):\n#     x_train_sequences.append(seq)\n\n# # Post-pad shorter sequences with 0 \n# max_length = max([len(i) for i in x_train_sequences])\n# x_train_tokenised = np.array(pad_sequences(x_train_sequences, maxlen=max_length, padding='post'))\n\n# print('----------\nx_train_tokenised:\n', x_train_tokenised)\n# Output looks like this:\n#   [[ 8  9 10 11 12  0  0  0  0  0  0]\n#    [ 1  2  3  4  5 13 14  6  7 15 16]]\n"

In [ ]:
### Print out the frequency of each word in a sentence 

# vocabulary = vectorizer.get_feature_names()
# # Get the frequency of each word in the sentence
# word_frequencies = feature_vectors.toarray()[0]

# # Print the word and its frequency
# for word, frequency in zip(vocabulary, word_frequencies):
#     print(f"Word: {word}, Frequency: {frequency}")

In [26]:
# Split data
x_train, x_test, y_train, y_test = train_test_split(x_train_feature_vectors, y_train, test_size=0.2, random_state=42)
# x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size=0.5, random_state=42)

In [38]:
# Train

# Step 4: Train the Naive Bayes classifier and make predictions
classifier = GaussianNB()
classifier.fit(x_train.toarray(), y_train)
predictions = classifier.predict(x_test.toarray())

print(f'x_test: {vectorizer.inverse_transform(x_test)}')
print(f'Predictions: {predictions}')
print(f'y_test: {y_test}')


# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy}")

mse = mean_squared_error(y_test, predictions)
rmse = mse ** 0.5
print(f"Root Mean Squared Error (RMSE): {rmse}")


# Val



# Test




# Continual Learning?

x_test: [array(['hi', 'rondo'], dtype='<U10'), array(['bla', 'blo', 'cluoud', 'discovered', 'gjango', 'hardware',
       'phone', 'pi', 'react', 'tech', 'web'], dtype='<U10')]
Predictions: [5. 4.]
y_test: 0    10.0
1     8.0
Name: grade, dtype: float64
Accuracy: 0.0
Root Mean Squared Error (RMSE): 4.527692569068709
